### ISSUE TITLE
Swagger to Ballerina example error

### ISSUE THREAD

**Issue by knightbeat** [ballerina-attic/tool-swagger-ballerina#82]
When this documentation is followed [https://ballerina.io/learn/by-example/swagger-to-ballerina.html](https://ballerina.io/learn/by-example/swagger-to-ballerina.html) the given example as it is does not work.

**Terminal command and the output:**
ballerina swagger mock swagger_to_ballerina.yaml -p pet_service
ballerina: Error occurred when generating MOCK for swagger file at swagger_to_ballerina.yaml. mock.

**Comment by chamil321** [comment]
@knightbeat Please create this issue in https://github.com/ballerina-platform/ballerina-examples as this repo no longer active
